### ISSUE TITLE
setup on localhost

### ISSUE THREAD

**Issue by d-bohn** [debruine/webmorph#2]
Thanks for supplying the code for this, and the work you put into it! I've used JPsychoMorph in our lab for years, so naturally I was/am excited to try this version.

I am trying to setup an instance of webmorph on my local machine (macOS Mojave) and ran into a bit of an issue. I followed the instructions on your README and everything appeared to work, but when I go to `webmorph.test` or `localhost` my browser takes me to a webpage that simply states "It works!". When I add `:8080` it takes me to the tomcat webpage stating it was successfully installed. I'm not a web developer, so this is fairly new to me. I'm just curious if I overlooked a step, or missed something that might be an easy fix since you went though this before.

I did notice that I am running an newer version of `php` than what you mention in your docs (7.x vs 5.x), though I'm not sure that should matter?

**Comment by debruine** [comment]
Oh no, I just saw this!

Local server problems are really difficult to debug remotely. Did you sort it or give up?

Are you not able to use the free web version on my server (webmorph.org)? If you sign up with an academic email you get an account immediately.
